name: publish

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: volta-cli/action@v1

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - run: pnpm build
      - run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          pnpm package
          pnpm publish --tag next ./package

      - run:
          if: startsWith(github.ref, 'refs/tags/v')
          pnpm publish ./package

        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}