name: publish

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  publish-npm:
    # if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: volta-cli/action@v1

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - run: pnpm build
      - run: pnpm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}